server:
  port: 8081
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/UserMovieDetails_Db_v1
  application:
    name: user-movie-services
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_IP:localhost}:${EUREKA_SERVER_PORT:8761}/eureka
    fetchRegistry: true
    registerWithEureka: true